awk -f sorter.awk BLIND_DATA1 > BLIND_TIME
awk -f sorter.awk FACEBOOK_DATA1 > FACE_TIME
awk -f sorter.awk POKEMONGO_DATA1 > POKE_TIME
awk -f process.awk BLIND_TIME > BLIND_SORT
awk -f process.awk FACE_TIME > FACE_SORT 
awk -f process.awk POKE_TIME > POKE_SORT 
sort -n BLIND_SORT > BLIND_SORT_MISSES
sort -n FACE_SORT > FACE_SORT_MISSES 
sort -n POKE_SORT > POKE_SORT_MISSES
awk -f FIXERUPPER.awk BLIND_SORT_MISSES > BLIND_CDF
awk -f FIXERUPPER.awk FACE_SORT_MISSES > FACE_CDF
awk -f FIXERUPPER.awk POKE_SORT_MISSES > POKE_CDF